# -*- coding: utf-8 -*-
"""MM226_Assignment_1_Group_5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GB9S9iZFzQk0MmG9D0T0pbFuh5ujTsyW
"""

import pandas as pd
import json
from google.colab import files

def convert_csv_to_json(file_name):
    # Reading the CSV file into a DataFrame
    df = pd.read_csv(file_name, encoding='latin1')

    # Converting the DataFrame to JSON format
    json_data = df.to_json(orient='records', indent=4)
    json_file_name = file_name.replace('.csv', '.json')

    # Saving the JSON file
    with open(json_file_name, 'w') as json_file:
        json_file.write(json_data)

    print(f"Converted {file_name} to {json_file_name}")
    return json_file_name

# Uploading CSV files
print("Please upload your CSV files:")
uploaded_files = files.upload()

# Processing each uploaded file and converting it to JSON
json_files = []
for file_name in uploaded_files.keys():
    json_file = convert_csv_to_json(file_name)
    json_files.append(json_file)

# Downloading the converted JSON files
print("\nDownloading JSON files...")
for json_file in json_files:
    files.download(json_file)

print("All files have been converted and downloaded successfully!")